### ISSUE TITLE
Photos app not using preloaded thumbnails

### ISSUE THREAD

**Issue by bmnielsen** [Mfarooq360/WinThumbsPreloader-V2#8]
I have a 1TB photo library (approx. 200,000 photos) that I am syncing from iCloud to my Windows 11 machine. I want to use the Photos app just for viewing on a larger screen that what we otherwise have on our Apple devices.

However since Photos doesn't automatically save thumbnails for all of the photos, the user experience is quite poor, as every time I scroll it spends 5-10 seconds before everything is rendered.

Google searches brought me to this project. I downloaded it, changed the configuration settings to generate both 256 and 768 thumbnail sizes, and set it to work on my library.

After a half day or so it finished processing everything, but when I use the Photos app I am not seeing any difference - scrolling to a new page causes it to wait for thumbnail generation again.

Looking at the resource monitor, WinThumbsPreloader is writing to the files I would expect (the 256 and 768 thumbnail caches), and indeed Photos is also writing to the same 768 file itself when it generates the thumbnails. So I'm not really sure why it isn't just using the thumbnails that were previously stored by WinThumbsPreloader.

Any ideas on what could be going wrong?

**Comment by VL4DST3R** [comment]
(Not the author but) This indeed may very well be a bug. Have you checked both the new and "legacy" versions of the photos app? Maybe it works only with the latter. Also that's a very long time for 200.000 photos, even if they are that large, have you used the multithreaded option when generating?

**Comment by bmnielsen** [comment]
I will try the legacy Photos app and see if that is any different.

I have multithreading enabled, but my photo library is on a couple of old 5400 RPM HDDs so I think it just took that long to read all of the data.

**Comment by bmnielsen** [comment]
I can confirm that the thumbnails are working in Photos Legacy - so I guess something has changed in how the thumbnails are handled between the two versions!
