### ISSUE TITLE
Cache get reset preloading Portable Hard Drive Folder

### ISSUE THREAD

**Issue by moxin3** [Mfarooq360/WinThumbsPreloader-V2#9]
Hi, my cache get reset if i add new folder from Portablle Hard Drive. Moreover, is it possible to skip previously preloaded files and preload new files or changes in the folder / drive

Regards

**Comment by VL4DST3R** [comment]
> Hi, my cache get reset if i add new folder from Portablle Hard Drive. 

Cached thumbs from removable storage gets removed when the device is removed, similar to indexing. It is sadly how windows operates for as long as i can remember, you cannot prevent it.

> is it possible to skip previously preloaded files and preload new files or changes in the folder / drive

Thumbs are not being remade if they are already found in the cache db, but the files themselves still have to be accessed by the program to confirm that they have been indeed cached, so it takes a bit of time regardless. On hard-drives this can indeed take some time as the seek time of the disk itself takes a while. On SSDs on the other hand it's virtually instant (or at least orders of magnitude faster)

**Comment by moxin3** [comment]
> > Hi, my cache get reset if i add new folder from Portablle Hard Drive.
> 
> Cached thumbs from removable storage gets removed when the device is removed, similar to indexing. It is sadly how windows operates for as long as I can remember, you cannot prevent it. Or is that not what you're referring to?
> 
> > is it possible to skip previously preloaded files and preload new files or changes in the folder / drive
> 
> Thumbs are not being remade if they are already found in the cache db, but the files themselves still have to be accessed by the program to confirm that they have been indeed cached, so it takes a bit of time regardless. On hard-drives this can indeed take some time as the seek time of the disk itself takes a while. On SSDs on the other hand it's virtually instant (or at least orders of magnitude faster)

Thanks i was asking same it answered my question and confusion
